export const metadata = { title: 'Privacy Policy | Anicca' };

export default function PrivacyEN() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-24">
      <h1 className="text-3xl font-bold text-foreground">Privacy Policy</h1>
      <p className="mt-6 text-muted-foreground">
        This policy describes how we handle user data, including personal information, in the Anicca iOS app (the &quot;Service&quot;).
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">1. Business Information</h2>
      <p className="mt-3 text-muted-foreground">Daisuke Narita (Individual Business Owner) / keiodaisuke@gmail.com</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">2. Scope of Application</h2>
      <p className="mt-3 text-muted-foreground">
        This policy applies to the Service and related support communications. It also applies to our website pages that link to this policy.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">3. Information We Collect</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Device identifiers (e.g., identifierForVendor / device-id) used for basic functionality and fraud/abuse prevention</li>
        <li>Optional account information from Sign in with Apple (Apple user identifier; email/name only if provided)</li>
        <li>In-app settings and preferences (e.g., selected problems, language preference)</li>
        <li>App usage/analytics events (e.g., onboarding progress, paywall events, notification interactions)</li>
        <li>Subscription status information (managed via App Store / RevenueCat)</li>
        <li>Support communications (e.g., emails you send to our support address)</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">4. Main Collection Methods</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Information you enter in the app</li>
        <li>Information generated by your interactions with the app (events/logs)</li>
        <li>Information received from the App Store and our subscription infrastructure (RevenueCat)</li>
        <li>Support inquiries sent to our support desk</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">5. Purpose of Use</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Provide and improve the Service</li>
        <li>Deliver notifications you opt into and measure engagement to improve them</li>
        <li>Manage subscriptions and entitlement status</li>
        <li>Analytics, debugging, and security measures</li>
        <li>Respond to support inquiries and send important notices</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">6. Third-Party Provision and Outsourcing</h2>
      <p className="mt-3 text-muted-foreground">
        We use the following vendors to operate the Service. Information may be transmitted to them as necessary for service provision.
      </p>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Apple (App Store billing, Sign in with Apple, SKAdNetwork attribution, and related platform services)</li>
        <li>RevenueCat (subscription/entitlement management)</li>
        <li>Superwall (paywall presentation and related analytics)</li>
        <li>Mixpanel (product analytics)</li>
        <li>Singular (mobile measurement/attribution)</li>
        <li>Railway / hosting providers (API hosting and operational logs)</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">7. ATT (App Tracking Transparency)</h2>
      <p className="mt-3 text-muted-foreground">
        If you grant tracking permission, an advertising identifier (IDFA) may be used for measurement and attribution. You can use the Service even if you do
        not grant permission.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">8. Data We Do Not Collect</h2>
      <p className="mt-3 text-muted-foreground">
        The Service does not access HealthKit data, motion/activity data, or Screen Time data.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">9. Retention Period and Deletion</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Identifiers on device: Reset when the app is deleted (IDFV behavior)</li>
        <li>Authentication tokens (if any): Stored on device and deleted upon logout or invalidation</li>
        <li>Support history: Stored for a reasonable period to respond and maintain records</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">10. Security Measures</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Secure communication (HTTPS/TLS)</li>
        <li>Appropriate access controls and operational monitoring</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">11. User Rights</h2>
      <p className="mt-3 text-muted-foreground">
        Users can request disclosure, correction, suspension of use, or deletion of their information. Please contact keiodaisuke@gmail.com.
      </p>

      <h3 className="mt-6 text-lg font-semibold text-foreground">Account Deletion (iOS)</h3>
      <p className="mt-3 text-muted-foreground">
        If the app provides an account deletion function, you can complete it within the app from the account section.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">12. Cookies</h2>
      <p className="mt-3 text-muted-foreground">The landing page uses only the minimum necessary cookies. Cookies themselves do not contain personal information.</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">13. Use by Minors</h2>
      <p className="mt-3 text-muted-foreground">Users under 13 years of age cannot use this service without parental consent.</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">14. Compliance</h2>
      <p className="mt-3 text-muted-foreground">We comply with the Personal Information Protection Act and other related laws and guidelines.</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">15. Revisions</h2>
      <p className="mt-3 text-muted-foreground">When revisions are made, we will announce them on this page, and important changes will be notified through in-app notifications, etc.</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">16. Contact</h2>
      <p className="mt-3 text-muted-foreground">Please contact keiodaisuke@gmail.com.</p>

      <p className="mt-12 text-right text-sm text-muted-foreground">Last Updated: January 26, 2026</p>
    </main>
  );
}










