@startuml
title Userオブジェクトのステートマシン図

[*] --> 未登録

未登録 : entry / 新規ユーザー
未登録 : do / 登録待ち

未登録 --> 登録済み : ユーザー登録

登録済み : entry / 利用可能
登録済み : do / 本を借りる/返す

登録済み --> 利用停止 : 利用停止
利用停止 --> 登録済み : 利用再開

登録済み --> 登録解除 : 登録解除
利用停止 --> 登録解除 : 登録解除

登録解除 : entry / 削除処理
登録解除 --> [*] : 削除完了

@enduml



