name: Release Stable (macOS)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (include dev)
        run: npm ci --include=dev

      - name: Build and Publish (stable)
        run: |
          npm run build:voice
          NODE_ENV=production npx electron-builder --mac --config electron-builder-voice.yml --publish always \
            -c.publish.releaseType=release
